name: "Next Release NPM Publisher"
description: "Versions your package.json and publishes to npm"
inputs:
  path:
    description: 'filepath to package.json, relative to your repo root'
    required: true
    default: "package.json"
  token:
    required: true
    description: "${{ secrets.GITHUB_TOKEN }}"
  use_pullrequest:
    default: false
    description: 'Use a pull request to generate the changelog instead of a direct commit'
  branch_name:
    required: false
    description: 'The branch name to use for a pull request for your changelog (If `use_pullrequest` is true)'
  default_branch:
    required: false
    description: 'The branch name to commit / make pull request against for changelog if different than the tagged branch'


runs:
  using: "node12"
  main: "dist/index.js"

branding:
  color: "blue"
  icon: "package"
